# Day 3 exercises

In [1]:
#q1

my_name = 'AlexBushnell'

if len(my_name)<10:
    print('My name is short')
elif len(my_name)>17:
    print('My name is long')
else:
    print('My name is average length')

My name is average length


In [4]:
#q2

import os 
x = os.listdir('C:\\')
my_list = []
for i in x:
    my_list.append(i)
    
my_list    

['$Recycle.Bin',
 'Documents and Settings',
 'hiberfil.sys',
 'Intel',
 'pagefile.sys',
 'PerfLogs',
 'Program Files',
 'Program Files (x86)',
 'ProgramData',
 'Recovery',
 'swapfile.sys',
 'System Volume Information',
 'Users',
 'Windows']

In [5]:
new_list=[]
for i in my_list:
    try:
        i.index(' ')
        pass 
    except:
        new_list.append(i)
        
new_list

['$Recycle.Bin',
 'hiberfil.sys',
 'Intel',
 'pagefile.sys',
 'PerfLogs',
 'ProgramData',
 'Recovery',
 'swapfile.sys',
 'Users',
 'Windows']

In [11]:
#q3
import random

random_no = random.randint(1,20)
count = 0

while random_no != 20:
    count = count + 1
    random_no = random.randint(1,20)
print(count) #this counts the amount of draws

1


In [32]:
#q3
import random
import statistics

random_no = random.randint(1,20)
count = 0
draws = []

for i in range(0,100):
    random_no = random.randint(1,20)
    count = 0
    while random_no != 20:
        count = count + 1
        random_no = random.randint(1,20)
    draws.append(count)
print(draws)
print('--------------------')
print(statistics.mean(draws)) 

[131, 24, 15, 7, 6, 4, 20, 63, 24, 6, 2, 13, 4, 64, 16, 0, 13, 14, 3, 47, 8, 13, 16, 6, 3, 13, 51, 14, 3, 17, 6, 5, 15, 18, 1, 0, 37, 5, 36, 16, 11, 16, 66, 4, 28, 2, 33, 1, 15, 87, 8, 23, 16, 53, 1, 22, 2, 14, 4, 1, 28, 18, 23, 0, 37, 10, 0, 35, 3, 27, 16, 33, 10, 2, 0, 9, 36, 88, 10, 2, 73, 38, 23, 33, 22, 10, 3, 43, 29, 33, 19, 56, 18, 11, 19, 3, 24, 5, 5, 18]
--------------------
20.38


In [25]:
# q4

try:
    f=open(r'C:\Users\AlexBushnell\Documents\Python Scripts\names5.txt','r')
except FileNotFoundError:
    print('File not found error')
except:
    print('Who knows what is up')

File not found error


In [125]:
# q5
import math
#1/0 #zerodivisionerror
try:
    math.log(0)
except FileNotFoundError:
    print('File not found error')
except ArithmeticError:
    print('Arithmetic error')
except SyntaxError:
    print('Syntax error')
except LookupError:
    print('Lookup error')
except RuntimeError:
    print('Runtime error')
except OSError:
    print('Syntax error')
except LookupError:
    print('Syntax error')
except ValueError:
    print('Value error')
except:
    print('Who knows what is up')

Value error


In [39]:
(-1)**(1/2)

(6.123233995736766e-17+1j)

In [51]:
# q6

my_list = [0] #true
my_tuple = (0,) #true
my_int = 0 #false


my_tuple2 = 0, #still true though

not not my_list
not not my_tuple
not not my_int

False

In [60]:
# q7


def elementwise_div(num,denom):
    results=[]
    for i in range(len(num)):
        try:
            results.append(num[i]/denom[i])
        except ZeroDivisionError:
            results.append(None)
        except:
            results.append(None)
    print(results)
    
elementwise_div([1,'3',10],[2,5,0]) #elementwise_div([1,3,10],[2,5,0]), elementwise_div([1,3,10],[2,5,2]) 
#all work

[0.5, None, None]


In [83]:
# q8

def compare_numbers(x,y):
    if x==y:
        print(f'{x} and {y} have the same sign and the same magnitude')
    elif abs(x)==abs(y):
        print(f'{x} and {y} have different sign but the same magnitude')
    elif x and y < 0:
        if y and x < 0:
            print(f'{x} and {y} have the same sign but different magnitude')
        else:
            print(f'{x} and {y} have different sign and different magnitude')
        
    elif x and y > 0:
        if y and x > 0:
            print(f'{x} and {y} have the same sign but different magnitude')
        else:
            print(f'{x} and {y} have different sign and different magnitude')

compare_numbers(1,-3)

1 and -3 have different sign and different magnitude


False

### Noughts and crosses

In [116]:
import numpy 
def create_board():
    board = numpy.zeros((3,3), dtype=int)
    return board
    

board = create_board()

[[0 0 0]
 [0 0 0]
 [0 0 0]]


NoneType

In [117]:
#place you first go whereever you choose
def place(board, player, position):
    if board[position[0]][position[1]] == 0:
        board[position[0]][position[1]] = player
    else:
        print('Invalid move')
    return board    
place(board,1,(0, 0))

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [121]:
def options(board):
    return numpy.where(board==0)
options(board)

2

In [ ]:
import random
def random_place(board,player):
    spot = random.randint(0,9)
    if spot - 2 < 0:
        if board[position[0],position[spot]] == 0:
            board[position[0],position[spot]] = player
        else:
            print('Position taken')
            pass
        
            


In [124]:
for i in range(1,10):
    r = random.randint(1,10)
    print(r)

4
9
2
1
7
4
5
6
7


[[0 0 0]
 [0 0 0]
 [0 0 0]]


numpy.ndarray